import fs from 'node:fs';
import { pathToFileURL } from 'node:url';
const modules=process.env.NODE_PATH;
if(!modules)throw new Error('NODE_PATH에 marked가 설치된 node_modules 경로를 지정하세요.');
const {marked}=await import(pathToFileURL(modules+'/marked/lib/marked.esm.js'));
const catalog=JSON.parse(fs.readFileSync('data/goods.json','utf8'));
const {goods}=catalog;
const categories=[...new Set(goods.map(p=>p.category))];
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const md=s=>String(s).replaceAll('|','\\|').replaceAll('\n',' ');
const yen=n=>'¥'+n.toLocaleString('en-US');
let checklist=`# 나라콘 굿즈 구매 체크리스트\n\n[전체 공연 가이드](README.md) · [휴대폰용 HTML](index.html)\n\n> 확인일 **2026-10-03** · 공식 공개 목록을 색상별로 나눈 **${goods.length}개 항목**입니다. 가격은 세금 포함 엔화입니다. 한국어 이름은 알아보기 위한 비공식 번역이며 원문을 함께 표기했습니다.\n\n수량·구매 완료·사이즈/메모 칸을 직접 편집해 사용하세요. **MD의 칸은 입력창이 아니므로 파일 편집이 필요합니다.** HTML에서는 수량 입력, 합계 계산, 구매 완료 표시, 기기 저장이 됩니다. 색상별로 한 줄이며 사이즈가 여러 개면 메모에 <code>M 1개 / L 2개</code>처럼 적으세요.\n\n상품 링크는 확인용입니다. 공연장 사전 수령 주문은 [MART for live 안내](https://zutomayo.net/bunka_denrai_Item_netorder/)에서 날짜·수령 시간을 선택하세요. 팝업 한정색·구상품·추첨 공예품은 판매 방법이 다릅니다. 구매 가능 여부는 재고와 공식 판매 공지를 확인하세요.\n\n사진은 공식 원격 이미지이며 인터넷 연결이 필요합니다. 이미지를 누르면 크게 볼 수 있습니다. 챔피언십 티셔츠 2색은 개별 사진·상세 링크를 확인하지 못해 공식 팝업 목록을 연결했습니다. 단품 엽서 3종은 3장 세트의 구성 사진을 사용했습니다.\n\n`;
const collections=[['tour','이번 공연 굿즈'],['legacy','이전 투어·기존 굿즈'],['cards','카드·음반']];
checklist+='이번 공연 굿즈와 이전 투어·기존 굿즈를 아래의 별도 표로 나눴습니다. 카드·음반은 신규·기존 상품을 함께 다루는 별도 목록입니다. HTML은 이번 공연 굿즈를 기본으로 보여줍니다.\n\n';
for(const [group,label] of collections){checklist+=`## ${label} (${goods.filter(p=>p.collection===group).length}개 항목)\n\n`;for(const c of categories){if(!goods.some(p=>p.collection===group&&p.category===c))continue;checklist+=`### ${c}\n\n| 사진 | 한국어 이름 · 원문 · 공식 링크 | 단가 | 판매 구분 · 참고 | 수량 | 구매 완료 | 사이즈 / 메모 |\n|---|---|---:|---|---:|:---:|---|\n`;for(const p of goods){if(p.category!==c||p.collection!==group)continue;const image=p.images.length?`<a href="${esc(p.images[0])}"><img src="${esc(p.images[0])}" width="90" alt="${esc(p.ko)}"></a>`:'사진 미확인';const title=`**${md(p.ko)}**<br>${md(p.name)}<br>[${md(p.code)} · ${p.linkType}](${p.url})`;const info=md(p.scope)+(p.size?'<br>규격: '+md(p.size):'')+(p.notes?'<br>'+md(p.notes):'');checklist+=`| ${image} | ${title} | ${yen(p.price)} | ${info} | \\_\\_\\_ | ☐ | \\_\\_\\_ |\n`;}checklist+='\n';}}
checklist+=`## 가격·판매 구분 메모\n\n- 합계에는 사전 수령 서비스 이용료 ¥220 및 배송비를 포함하지 않습니다. 서비스 이용료는 주문 안내의 적용 단위를 확인하세요.\n- 팝업 한정색은 공연장 판매 대상에서 제외됩니다. 헨리넥은 최신 현장·팝업 목록의 **Ice Blue 한정 / Nerd Blue 일반** 표기를 사용했습니다.\n- 과자 ZMY925 / ZMY926은 정적 상품 데이터와 안내 본문 가격이 달라, 안내 본문과 상품 상세의 **¥1,800 / ¥1,600**을 사용했습니다.\n- Re:HP 티셔츠는 온라인 상품 가격과 팝업 공지 가격이 달라 **팝업 공지 ¥5,600**을 사용했습니다.\n- 명장 공예 4종은 전시 후 추첨 판매이며 일반 굿즈 주문과 구분됩니다.\n- 의류의 Short는 별도 길이 옵션입니다. 실측과 선택 가능한 사이즈는 상품 상세에서 확인하세요.\n\n출처: [현장 수령·신상품](${catalog.sources.current}) · [사전 공개 목록](${catalog.sources.pre}) · [나라 팝업 전체 판매 목록](${catalog.sources.popup}) · [공연·명장 협업](${catalog.sources.craft}) · 각 행의 공식 상품 상세.\n`;
fs.writeFileSync('GOODS_CHECKLIST.md',checklist);
const slug=s=>s.toLowerCase().replace(/[^\p{L}\p{N}\p{M}_\-\s]/gu,'').replaceAll(' ','-');
const ids=new Map();const renderer=new marked.Renderer();
renderer.heading=function({tokens,depth}){const text=this.parser.parseInline(tokens);const plain=text.replace(/<[^>]+>/g,'');const base=slug(plain);const n=ids.get(base)||0;ids.set(base,n+1);return `<h${depth} id="${esc(base+(n?'-'+n:''))}">${text}</h${depth}>\n`;};
let guide=marked.parse(fs.readFileSync('README.md','utf8'),{gfm:true,renderer});
guide=guide.replaceAll('<table>','<div class="table-scroll" tabindex="0" role="region" aria-label="가로 스크롤 표"><table>').replaceAll('</table>','</table></div>');
guide=guide.replace(/<a href="(https:[^"]+)"/g,'<a href="$1" target="_blank" rel="noopener noreferrer"');
const css=fs.readFileSync('assets/style.css','utf8');
const js=fs.readFileSync('assets/app.js','utf8');
const template=fs.readFileSync('assets/page.html','utf8');
const data=JSON.stringify(catalog).replaceAll('<','\\u003c');
fs.writeFileSync('index.html',template.replace('/* INLINE_CSS */',()=>css).replace('<!-- GUIDE -->',()=>guide).replace('/* INLINE_DATA */',()=>`const CATALOG=${data};`).replace('/* INLINE_APP */',()=>js));
console.log(JSON.stringify({goods:goods.length,photos:goods.filter(p=>p.images.length).length,guideTables:(guide.match(/<table>/g)||[]).length,htmlBytes:fs.statSync('index.html').size,mdBytes:fs.statSync('GOODS_CHECKLIST.md').size}));
