const {chromium}=require('playwright');
const fs=require('node:fs');
const assert=require('node:assert/strict');
const goods=JSON.parse(fs.readFileSync('data/goods.json','utf8')).goods;
const base='http://127.0.0.1:4174';
const yen=n=>'¥'+n.toLocaleString('en-US');
(async()=>{
fs.mkdirSync('.preview',{recursive:true});
const server=require('node:http').createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(fs.readFileSync('index.html'));});
await new Promise(resolve=>server.listen(4174,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,hasTouch:true,isMobile:true,acceptDownloads:true});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base,{waitUntil:'domcontentloaded'});
assert.equal(await page.locator('.good-card').count(),140);
assert.equal(await page.locator('#budget-total').textContent(),'¥0');
assert.equal(await page.locator('.good-card[data-id="ZMY718"]').count(),0);
await page.locator('[data-collection="legacy"]').click();assert.equal(await page.locator('.good-card').count(),59);assert.equal(await page.locator('.good-card[data-id="ZMY718"]').count(),1);assert.equal(await page.locator('.good-card[data-id="ZMY785"]').count(),0);assert.equal(await page.locator('.good-card[data-id="POSTCARD-0"]').count(),0);
await page.locator('.good-card [data-qty][data-id="ZMY718"]').fill('1');
await page.locator('[data-collection="cards"]').click();assert.equal(await page.locator('.good-card').count(),35);assert.equal(await page.locator('.good-card[data-id="ZMY088"]').count(),1);
await page.locator('[data-collection="all"]').click();assert.equal(await page.locator('.good-card').count(),234);
await page.locator('.tabs [data-tab="plan"]').click();assert.equal(await page.locator('.plan-row').count(),1);await page.locator('[data-remove="ZMY718"]').click();
await page.locator('.tabs [data-tab="catalog"]').click();await page.locator('[data-collection="tour"]').click();assert.equal(await page.locator('.good-card[data-id="POSTCARD-0"]').count(),1);
const product=goods.find(p=>p.code==='ZMY785');
await page.locator('#search').fill('ZMY785');
await page.waitForFunction(()=>document.querySelectorAll('.good-card').length===1);
await page.locator('.good-card [data-size]').selectOption('M');
await page.locator('.good-card [data-details]').click();
assert.equal(await page.locator('#product-details').evaluate(e=>e.open),true);
assert.equal(await page.locator('#details-body .spec-table tbody tr').count(),5);
assert((await page.locator('#details-body .spec-table tbody tr').first().textContent()).includes('총장 57cm'));
assert((await page.locator('#details-body').textContent()).includes('사전 주문 → 공연장 수령'));
await page.screenshot({path:'.preview/mobile-size-details.png',fullPage:false});
await page.locator('#close-details').click();
await page.locator(`[data-qty][data-id="${product.id}"]`).fill('2');
await page.locator(`[data-memo][data-id="${product.id}"]`).fill('M 1개 / L 1개');
assert.equal(await page.locator('#budget-total').textContent(),yen(product.price*2));
await page.locator(`[data-bought][data-id="${product.id}"]`).check();
await page.reload({waitUntil:'domcontentloaded'});
assert.equal(await page.locator(`.good-card [data-qty][data-id="${product.id}"]`).inputValue(),'2');
assert.equal(await page.locator(`.good-card [data-memo][data-id="${product.id}"]`).inputValue(),'M 1개 / L 1개');
assert.equal(await page.locator(`.good-card [data-bought][data-id="${product.id}"]`).isChecked(),true);
assert.equal(await page.locator(`.good-card [data-size][data-id="${product.id}"]`).inputValue(),'M');
await page.locator('.tabs [data-tab="plan"]').click();
assert.equal(await page.locator('.plan-row').count(),1);
assert.equal(await page.locator('.plan-row [data-size]').inputValue(),'M');
assert.equal(await page.locator('#metric-bought').textContent(),yen(product.price*2));
assert.equal(await page.locator('#metric-remaining').textContent(),'¥0');
await page.screenshot({path:'.preview/mobile-plan.png',fullPage:true});
let downloaded=page.waitForEvent('download');await page.locator('#export-md').click();let file=await downloaded;await file.saveAs('.preview/purchase.md');const md=fs.readFileSync('.preview/purchase.md','utf8');assert(md.includes('| 2 |'));assert(md.includes('M / M 1개 / L 1개'));assert(md.includes('☑'));assert(md.includes(product.url));
downloaded=page.waitForEvent('download');await page.locator('#export-json').click();file=await downloaded;await file.saveAs('.preview/backup.json');assert.equal(JSON.parse(fs.readFileSync('.preview/backup.json','utf8')).state[product.id].qty,2);assert.equal(JSON.parse(fs.readFileSync('.preview/backup.json','utf8')).state[product.id].size,'M');
await page.locator('#reset-plan').click();await page.locator('#confirm-reset').click();assert.equal(await page.locator('.plan-row').count(),0);
await page.locator('#import-file').setInputFiles('.preview/backup.json');await page.locator('#confirm-reset').click();assert.equal(await page.locator('.plan-row').count(),1);assert.equal(await page.locator('#budget-total').textContent(),yen(product.price*2));
assert.equal(await page.locator('.plan-row [data-size]').inputValue(),'M');
await page.locator('#import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"state":{}}')});await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('올바른'));assert.equal(await page.locator('.plan-row').count(),1);
await page.locator('.plan-row [data-qty]').fill('-4');await page.locator('.plan-row [data-memo]').click();assert.equal(await page.locator('.plan-row [data-qty]').inputValue(),'0');assert.equal(await page.locator('#budget-total').textContent(),'¥0');
await page.locator('.plan-row [data-qty]').fill('2');await page.locator('.plan-row [data-bought]').check();
await page.locator('.tabs [data-tab="catalog"]').click();await page.locator('#scope').selectOption('팝업 한정색');assert.equal(await page.locator('.good-card').count(),goods.filter(p=>p.scope==='팝업 한정색').length);
await page.locator('#clear-filters').click();await page.locator('#search').fill('ZMY785');await page.waitForFunction(()=>document.querySelectorAll('.good-card').length===1);
const image=page.locator('.image-button img');try{await image.waitFor({timeout:10000});await page.waitForFunction(()=>{const i=document.querySelector('.image-button img');return i?.complete&&i.naturalWidth>0;},{timeout:15000});}catch{}
const imageStatus=await page.evaluate(()=>{const i=document.querySelector('.image-button img');return{loaded:!!i?.naturalWidth,src:i?.src,fallback:!!document.querySelector('.image-button .photo-fallback')};});
await page.screenshot({path:'.preview/mobile-catalog.png',fullPage:true});
await page.locator('.image-button').click();assert.equal(await page.locator('#gallery').evaluate(e=>e.open),true);await page.locator('#next-image').click();assert.equal(await page.locator('#image-count').textContent(),`2 / ${product.images.length}`);await page.locator('#close-gallery').click();
await page.locator('[data-purchase-filter="lottery"]').click();assert.equal(await page.locator('.good-card').count(),4);
assert.equal(await page.locator('#pending-crafts').isVisible(),true);assert((await page.locator('#pending-crafts').textContent()).includes('도자기'));
await page.locator('[data-details="ZMY907"]').click();assert((await page.locator('#details-body').textContent()).includes('40개 한정'));assert((await page.locator('#details-body').textContent()).includes('추첨 접수 일정·방법·신청 링크 미공개'));assert.equal(await page.locator('#details-body .channel-detail').count(),1);await page.screenshot({path:'.preview/mobile-lottery-details.png'});await page.locator('#close-details').click();
await page.locator('[data-purchase-filter="additional"]').click();assert.equal(await page.locator('.good-card').count(),38);
await page.locator('#purchase').selectOption('station');assert(await page.locator('.good-card[data-id="ZMY890"]').count());assert.equal(await page.locator('.good-card[data-id="ZMY907"]').count(),0);
await page.locator('#clear-filters').click();await page.locator('#search').fill('도자기');await page.waitForFunction(()=>document.querySelectorAll('.good-card').length===2);
await page.locator('#clear-filters').click();await page.locator('#search').fill('ZMY914');await page.waitForFunction(()=>document.querySelectorAll('.good-card').length===1);assert.deepEqual(await page.locator('.good-card [data-size] option').allTextContents(),['사이즈 선택','22.5cm~24cm','25.5cm~27cm','27cm~28.5cm','여러 사이즈']);
await page.locator('#clear-filters').click();await page.locator('#search').fill('ZMY785');await page.waitForFunction(()=>document.querySelectorAll('.good-card').length===1);
for(const width of [360,390,768,1440]){await page.setViewportSize({width,height:900});for(const tab of ['catalog','plan','guide']){await page.locator(`.tabs [data-tab="${tab}"]`).click();const dimensions=await page.evaluate(()=>({body:document.documentElement.scrollWidth,view:window.innerWidth}));assert(dimensions.body<=dimensions.view,`overflow ${width} ${tab}: ${JSON.stringify(dimensions)}`);}}
await page.locator('.tabs [data-tab="guide"]').click();assert.equal(await page.locator('.guide-content table').count(),38);await page.getByRole('link',{name:'공연과 티켓',exact:true}).click();await page.waitForFunction(()=>location.hash.includes('%EA%B3%B5')||decodeURIComponent(location.hash)==='#공연과-티켓');assert.equal(await page.locator('#guide').isVisible(),true);const anchors=await page.evaluate(()=>[...document.querySelectorAll('.guide-content a[href^="#"]')].map(a=>a.getAttribute('href').slice(1)).filter(id=>!document.getElementById(decodeURIComponent(id))));assert.deepEqual(anchors,[]);
await page.goto(base+'/#catalog',{waitUntil:'domcontentloaded'});await page.setViewportSize({width:1440,height:1000});await page.locator('#clear-filters').click();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'.preview/desktop.png',fullPage:false});await page.setViewportSize({width:390,height:844});await page.locator('#search').fill('ZMY785');await page.waitForFunction(()=>document.querySelectorAll('.good-card').length===1);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'.preview/mobile-top.png',fullPage:false});
const blocked=await browser.newContext({viewport:{width:390,height:844}});await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw Error('disabled')}}));const bpage=await blocked.newPage();await bpage.goto(base+'/#plan',{waitUntil:'domcontentloaded'});assert((await bpage.locator('#storage-note').textContent()).includes('자동 저장을 사용할 수 없습니다'));await blocked.close();
const oldContext=await browser.newContext();await oldContext.addInitScript(()=>localStorage.setItem('zutomayo-nara-2026-shopping-v1',JSON.stringify({ZMY785:{qty:3,memo:'예전 구매 메모',bought:true}})));const oldPage=await oldContext.newPage();await oldPage.goto(base+'/#plan',{waitUntil:'domcontentloaded'});assert.equal(await oldPage.locator('.plan-row [data-qty]').inputValue(),'3');assert.equal(await oldPage.locator('.plan-row [data-memo]').inputValue(),'예전 구매 메모');assert.equal(await oldPage.locator('.plan-row [data-bought]').isChecked(),true);assert.equal(await oldPage.locator('.plan-row [data-size]').inputValue(),'');await oldContext.close();
const fileContext=await browser.newContext();const filePage=await fileContext.newPage();await filePage.goto('file:///'+process.cwd().replaceAll('\\','/')+'/index.html',{waitUntil:'domcontentloaded'});assert.equal(await filePage.locator('.good-card').count(),140);await fileContext.close();
assert.deepEqual(errors,[]);
console.log(JSON.stringify({passed:true,goods:234,viewports:[360,390,768,1440],tested:['current default','legacy separation','card separation','all groups','legacy quantity survives group switch','postcard classification','quantity','totals','bought','persistence','markdown export','backup import/export','invalid backup','negative quantity','filter','gallery','guide anchors','no overflow','unavailable storage','standalone file','Korean measurement table','shoe size choices','size persistence and backup','lottery conditions','station filter','additional release filter','ceramic search','legacy saved state compatibility'],imageStatus,pageErrors:errors},null,2));
await browser.close();
await new Promise(resolve=>server.close(resolve));
})().catch(e=>{console.error(e);process.exit(1)});
